### ISSUE TITLE
No search result in Search in SnippetsLab

### ISSUE THREAD

**Issue by akibarika** [atika/LaunchBar-Actions#2]
Hi there

First of all, thanks for those actions you created. They are really good

I just installed the Search in SnippetsLab action for my Launchbar 6.8 and my SnippetsLab version is 1.6.4. When I am typing words in the search box, there is no results show up.
My console log gives me: 
`SnippetsLabAction.rb:19:in <main>: undefined method each_element for nil:NilClass (NoMethodError)`

Please help, thanks :)

**Comment by atika** [comment]
Hello, thank you. Just see your message :grimacing:
An **update** of the **Snippet Lab Alfred workflow** break this LaunchBar Action Script... It worked very well before. I informed the developer if there is an addition to check for security purpose or anything else that break the usage of the program outside Alfred, and I never received a response...

**Comment by atika** [comment]
I reverse engineered the SnippetsLab app and effectively, the program check now that the source of the request is Alfred. That's for this that this action no longer works in LaunchBar.

**Comment by ptim** [comment]
thumbs up for your efforts, sad face that launchbar got the cold shoulder :(

**Comment by atika** [comment]
@akibarika @ptim I found a workaround, it's not perfect and need testing, but it seems to do the job for the moment  7c2e26f1b323a54a518bcad4d95fc9af8ed218a8
Download here: [Search in SnippetsLab Action 1.2](https://atika.github.io/launchbar/search-in-snippetslab-code-manager-for-mac-from-launchbar.html)

**Comment by ptim** [comment]
Thanks @atika! Thanks for persisting! I've installed the action, but when I invoke it, I get no results list (or noticeable effect)

In the console, I see:

> Search SnippetsLab (com.inspira.SearchSnippetsLab): Script Error: </usr/bin/env ruby /Users/ptim/Library/Application Support/LaunchBar/Actions/SearchSnippetsLab.lbaction/Contents/Scripts/SnippetsLabAction.rb nla>
LSOpenURLsWithRole() failed with error -10825 for the file /Users/ptim/Library/Application Support/LaunchBar/Actions/SearchSnippetsLab.lbaction/Contents/Scripts/Alfred.app.

...so I guess I do need alfred for this at present?

I had a reply from the SL dev Renfei, who said:

> The Alfred Workflow that shipped with SnippetsLab was updated in version 1.6.x, and the LaunchBar action stopped working since then. Perhaps the new script is not fully compatible with LaunchBar, but it is not my intention to block LaunchBar from using SnippetsLab’s script. In fact, adding official support for LaunchBar is in my roadmap for the future.

**Comment by atika** [comment]
@ptim Try to find the app that you log specify and **launch it manually**, and try again, normally it's OK as I signed the app. Maybe something block this little app to launch.
When you start a search this little app launch and emulate a Alfred window. There is a while that this action doesn't work now, SnippetsLab check for the presence of the Alfred window to give the results, without this window, the program hang...
